USE TMS;

DELIMITER $$

CREATE TRIGGER UPDATE_CREDIT_POINT_CAR
AFTER INSERT
ON BOOKS_CAR
FOR EACH ROW
BEGIN
	IF NEW.PRICE < 799 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 5;
	ELSEIF NEW.PRICE BETWEEN 800 AND 1000 THEN
		UPDATE CUSTOMER
		SET CREDIT_POINTS = CREDIT_POINTS + 10;
	ELSEIF NEW.PRICE BETWEEN 1001 AND 5000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 20;
	ELSE
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 40;
	END IF;
END $$

CREATE TRIGGER UPDATE_CREDIT_POINT_BUS
AFTER INSERT
ON BOOKS_BUS
FOR EACH ROW
BEGIN
	IF NEW.PRICE < 799 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 5;
	ELSEIF NEW.PRICE BETWEEN 800 AND 1000 THEN
		UPDATE CUSTOMER
		SET CREDIT_POINTS = CREDIT_POINTS + 10;
	ELSEIF NEW.PRICE BETWEEN 1001 AND 5000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 20;
	ELSEIF NEW.PRICE > 5000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 40;
	END IF;
END $$

CREATE TRIGGER UPDATE_CREDIT_POINT_FLIGHT
AFTER INSERT
ON BOOKS_FLIGHT
FOR EACH ROW
BEGIN
	IF NEW.PRICE < 799 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 5;
	ELSEIF NEW.PRICE BETWEEN 800 AND 1000 THEN
		UPDATE CUSTOMER
		SET CREDIT_POINTS = CREDIT_POINTS + 10;
	ELSEIF NEW.PRICE BETWEEN 1001 AND 5000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 20;
	ELSEIF NEW.PRICE > 5000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 40;
	END IF;
END $$

DELIMITER ;

