USE FMS;

DELIMITER $$

-- CREATE TRIGGER UPDATE_CREDIT_POINT_CAR
-- AFTER INSERT
-- ON BOOKS_CAR
-- FOR EACH ROW
-- BEGIN
-- 	IF NEW.PRICE < 799 THEN
-- 		UPDATE CUSTOMER
--         SET CREDIT_POINTS = CREDIT_POINTS + 5;
-- 	ELSEIF NEW.PRICE BETWEEN 800 AND 1000 THEN
-- 		UPDATE CUSTOMER
-- 		SET CREDIT_POINTS = CREDIT_POINTS + 10;
-- 	ELSEIF NEW.PRICE BETWEEN 1001 AND 5000 THEN
-- 		UPDATE CUSTOMER
--         SET CREDIT_POINTS = CREDIT_POINTS + 20;
-- 	ELSE
-- 		UPDATE CUSTOMER
--         SET CREDIT_POINTS = CREDIT_POINTS + 40;
-- 	END IF;
-- END $$

-- CREATE TRIGGER UPDATE_CREDIT_POINT_BUS
-- AFTER INSERT
-- ON BOOKS_BUS
-- FOR EACH ROW
-- BEGIN
-- 	IF NEW.PRICE < 799 THEN
-- 		UPDATE CUSTOMER
--         SET CREDIT_POINTS = CREDIT_POINTS + 5;
-- 	ELSEIF NEW.PRICE BETWEEN 800 AND 1000 THEN
-- 		UPDATE CUSTOMER
-- 		SET CREDIT_POINTS = CREDIT_POINTS + 10;
-- 	ELSEIF NEW.PRICE BETWEEN 1001 AND 5000 THEN
-- 		UPDATE CUSTOMER
--         SET CREDIT_POINTS = CREDIT_POINTS + 20;
-- 	ELSEIF NEW.PRICE > 5000 THEN
-- 		UPDATE CUSTOMER
--         SET CREDIT_POINTS = CREDIT_POINTS + 40;
-- 	END IF;
-- END $$

CREATE TRIGGER UPDATE_CREDIT_POINT_FLIGHT
AFTER INSERT
ON BOOKS_FLIGHT
FOR EACH ROW
BEGIN
	IF NEW.PRICE < 2000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 5 
        WHERE CUSTOMER.CUSTOMER_ID = NEW.CUSTOMER_ID;
	ELSEIF NEW.PRICE BETWEEN 2001 AND 3500 THEN
		UPDATE CUSTOMER
		SET CREDIT_POINTS = CREDIT_POINTS + 10
        WHERE CUSTOMER.CUSTOMER_ID = NEW.CUSTOMER_ID;
	ELSEIF NEW.PRICE BETWEEN 3501 AND 5000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 20
        WHERE CUSTOMER.CUSTOMER_ID = NEW.CUSTOMER_ID;
	ELSEIF NEW.PRICE > 5000 THEN
		UPDATE CUSTOMER
        SET CREDIT_POINTS = CREDIT_POINTS + 40
        WHERE CUSTOMER.CUSTOMER_ID = NEW.CUSTOMER_ID;
	END IF;
END $$

CREATE TRIGGER UPDATE_AVAILABILITY 
AFTER INSERT
ON BOOKS_FLIGHT 
FOR EACH ROW
BEGIN
	IF NEW.SEAT_TYPE = "FIRSTCLASS" THEN
		UPDATE JOURNEY_FLIGHT
        SET AVAILABLE_FIRSTCLASS_SEATS = AVAILABLE_FIRSTCLASS_SEATS - 1
        WHERE JOURNEY_FLIGHT.JOURNEY_ID = NEW.JOURNEY_ID;
	
    ELSEIF NEW.SEAT_TYPE = "ECONOMY" THEN
		UPDATE JOURNEY_FLIGHT
        SET AVAILABLE_ECONOMY_SEATS = AVAILABLE_ECONOMY_SEATS - 1
        WHERE JOURNEY_FLIGHT.JOURNEY_ID = NEW.JOURNEY_ID;
	ELSEIF NEW.SEAT_TYPE = "BUSINESS" THEN
		UPDATE JOURNEY_FLIGHT
        SET AVAILABLE_BUSINESS_SEATS = AVAILABLE_BUSINESS_SEATS - 1
        WHERE JOURNEY_FLIGHT.JOURNEY_ID = NEW.JOURNEY_ID;
	ELSEIF NEW.SEAT_TYPE = "PREMIUM" THEN
		UPDATE JOURNEY_FLIGHT
        SET AVAILABLE_PREMIUM_SEATS = AVAILABLE_PREMIUM_SEATS - 1
        WHERE JOURNEY_FLIGHT.JOURNEY_ID = NEW.JOURNEY_ID;
	END IF;

END $$


DELIMITER ;

